# Generated by Django 5.1.6 on 2026-05-13 00:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dentist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=150)),
                ('patient_phone', models.CharField(max_length=30)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_complaint', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('IN_REVIEW', 'IN REVIEW'), ('RESPONDED', 'RESPONDED'), ('RESOLVED', 'RESOLVED')], default='NEW', max_length=20)),
                ('dentist_diagnosis', models.TextField(blank=True, null=True)),
                ('dentist_treatment_plan', models.TextField(blank=True, null=True)),
                ('dentist_medications', models.TextField(blank=True, null=True)),
                ('dentist_follow_up', models.TextField(blank=True, null=True)),
                ('dentist_response_date', models.DateTimeField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('rating_comment', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='dentist.dentistprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_file', models.ImageField(upload_to='consultation_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='consultations.consultation')),
            ],
        ),
    ]
