# Generated by Django 5.1.6 on 2026-05-15 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('dentist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='follow_up_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='has_bleeding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='has_fever',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='has_swelling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='has_trauma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pain_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consultation',
            name='symptom_duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='consultation',
            name='triage_summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='consultation',
            name='urgency',
            field=models.CharField(default='ROUTINE', max_length=20),
        ),
        migrations.CreateModel(
            name='ResponseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('diagnosis', models.TextField()),
                ('treatment_plan', models.TextField()),
                ('medications', models.TextField(blank=True)),
                ('follow_up', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_templates', to='dentist.dentistprofile')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
