# Generated by Django 5.1.6 on 2026-05-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultation_follow_up_due_consultation_has_bleeding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='urgency',
            field=models.CharField(choices=[('URGENT', 'URGENT'), ('PRIORITY', 'PRIORITY'), ('ROUTINE', 'ROUTINE')], default='ROUTINE', max_length=20),
        ),
    ]
