# Generated by Django 5.1.6 on 2026-05-13 00:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DentistProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('specialty', models.CharField(blank=True, choices=[('General', 'General Dentistry'), ('Ortho', 'Orthodontics'), ('Prostho', 'Prosthodontics'), ('Pediatric', 'Pediatric Dentistry'), ('Oral Surgery', 'Oral Surgery'), ('Perio', 'Periodontics'), ('Endo', 'Endodontics'), ('Cosmetic', 'Cosmetic Dentistry'), ('Other', 'Other')], max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('lga', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.CharField(blank=True, max_length=200, null=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('response_time_hours', models.IntegerField(default=24)),
                ('notify_sms', models.BooleanField(default=True)),
                ('notify_email', models.BooleanField(default=True)),
                ('average_rating', models.FloatField(default=0.0)),
                ('total_consultations', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('public_slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
